name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Construir y levantar servicios
        run: docker compose up -d --build

      - name: Esperar a que los servicios despierten
        run: sleep 30

      - name: Prueba de Health Check
        run: |
          curl --retry 5 --retry-delay 5 http://localhost:3000/health

      - name: Prueba de Productos
        run: |
          curl http://localhost:3000/productos | grep "Teclado"
